// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: patient.proto
// Protobuf Java Version: 4.30.2
package com.healthcare.patient_service.service.grpc;
public final class PatientProto {
  private PatientProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      PatientProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PatientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PatientResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpatient.proto\"\034\n\016PatientRequest\022\n\n\002id\030" +
      "\001 \001(\t\"i\n\017PatientResponse\022\022\n\npatient_id\030\001" +
      " \001(\t\022\021\n\tfull_name\030\002 \001(\t\022\026\n\016contact_numbe" +
      "r\030\003 \001(\t\022\027\n\017medical_history\030\004 \001(\t2A\n\016Pati" +
      "entService\022/\n\nGetPatient\022\017.PatientReques" +
      "t\032\020.PatientResponseB\020B\014PatientProtoP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PatientRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PatientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PatientRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_PatientResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PatientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PatientResponse_descriptor,
        new java.lang.String[] { "PatientId", "FullName", "ContactNumber", "MedicalHistory", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
