// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: patient.proto
// Protobuf Java Version: 4.30.2
package com.healthcare.patient_service.service.grpc;
public interface PatientResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PatientResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string patient_id = 1;</code>
   * @return The patientId.
   */
  java.lang.String getPatientId();
  /**
   * <code>string patient_id = 1;</code>
   * @return The bytes for patientId.
   */
  com.google.protobuf.ByteString
      getPatientIdBytes();

  /**
   * <code>string full_name = 2;</code>
   * @return The fullName.
   */
  java.lang.String getFullName();
  /**
   * <code>string full_name = 2;</code>
   * @return The bytes for fullName.
   */
  com.google.protobuf.ByteString
      getFullNameBytes();

  /**
   * <code>string contact_number = 3;</code>
   * @return The contactNumber.
   */
  java.lang.String getContactNumber();
  /**
   * <code>string contact_number = 3;</code>
   * @return The bytes for contactNumber.
   */
  com.google.protobuf.ByteString
      getContactNumberBytes();

  /**
   * <code>string medical_history = 4;</code>
   * @return The medicalHistory.
   */
  java.lang.String getMedicalHistory();
  /**
   * <code>string medical_history = 4;</code>
   * @return The bytes for medicalHistory.
   */
  com.google.protobuf.ByteString
      getMedicalHistoryBytes();
}
