// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor_service.proto

// Protobuf Java Version: 3.25.3
package com.healthcare.doctor_service.service.grpc;

public interface AddAvailabilityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddAvailabilityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 slot_id = 1;</code>
   * @return The slotId.
   */
  long getSlotId();

  /**
   * <code>.google.protobuf.Timestamp start_time = 2;</code>
   * @return Whether the startTime field is set.
   */
  boolean hasStartTime();
  /**
   * <code>.google.protobuf.Timestamp start_time = 2;</code>
   * @return The startTime.
   */
  com.google.protobuf.Timestamp getStartTime();
  /**
   * <code>.google.protobuf.Timestamp start_time = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp end_time = 3;</code>
   * @return Whether the endTime field is set.
   */
  boolean hasEndTime();
  /**
   * <code>.google.protobuf.Timestamp end_time = 3;</code>
   * @return The endTime.
   */
  com.google.protobuf.Timestamp getEndTime();
  /**
   * <code>.google.protobuf.Timestamp end_time = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getEndTimeOrBuilder();
}
