// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor_service.proto

// Protobuf Java Version: 3.25.3
package com.healthcare.doctor_service.service.grpc;

public interface AddAvailabilityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddAvailabilityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string doctor_id = 1;</code>
   * @return The doctorId.
   */
  java.lang.String getDoctorId();
  /**
   * <code>string doctor_id = 1;</code>
   * @return The bytes for doctorId.
   */
  com.google.protobuf.ByteString
      getDoctorIdBytes();

  /**
   * <code>.google.protobuf.Timestamp start_time = 2;</code>
   * @return Whether the startTime field is set.
   */
  boolean hasStartTime();
  /**
   * <code>.google.protobuf.Timestamp start_time = 2;</code>
   * @return The startTime.
   */
  com.google.protobuf.Timestamp getStartTime();
  /**
   * <code>.google.protobuf.Timestamp start_time = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder();

  /**
   * <code>.google.protobuf.Duration duration = 3;</code>
   * @return Whether the duration field is set.
   */
  boolean hasDuration();
  /**
   * <code>.google.protobuf.Duration duration = 3;</code>
   * @return The duration.
   */
  com.google.protobuf.Duration getDuration();
  /**
   * <code>.google.protobuf.Duration duration = 3;</code>
   */
  com.google.protobuf.DurationOrBuilder getDurationOrBuilder();
}
