// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor_service.proto

// Protobuf Java Version: 3.25.3
package com.healthcare.doctor_service.service.grpc;

public interface DoctorListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DoctorList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Doctor doctors = 1;</code>
   */
  java.util.List<com.healthcare.doctor_service.service.grpc.Doctor> 
      getDoctorsList();
  /**
   * <code>repeated .Doctor doctors = 1;</code>
   */
  com.healthcare.doctor_service.service.grpc.Doctor getDoctors(int index);
  /**
   * <code>repeated .Doctor doctors = 1;</code>
   */
  int getDoctorsCount();
  /**
   * <code>repeated .Doctor doctors = 1;</code>
   */
  java.util.List<? extends com.healthcare.doctor_service.service.grpc.DoctorOrBuilder> 
      getDoctorsOrBuilderList();
  /**
   * <code>repeated .Doctor doctors = 1;</code>
   */
  com.healthcare.doctor_service.service.grpc.DoctorOrBuilder getDoctorsOrBuilder(
      int index);
}
