// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor_service.proto

// Protobuf Java Version: 3.25.3
package com.healthcare.doctor_service.service.grpc;

/**
 * Protobuf type {@code DoctorList}
 */
public final class DoctorList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DoctorList)
    DoctorListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DoctorList.newBuilder() to construct.
  private DoctorList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DoctorList() {
    doctors_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DoctorList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.healthcare.doctor_service.service.grpc.DoctorServiceOuterClass.internal_static_DoctorList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.healthcare.doctor_service.service.grpc.DoctorServiceOuterClass.internal_static_DoctorList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.healthcare.doctor_service.service.grpc.DoctorList.class, com.healthcare.doctor_service.service.grpc.DoctorList.Builder.class);
  }

  public static final int DOCTORS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.healthcare.doctor_service.service.grpc.Doctor> doctors_;
  /**
   * <code>repeated .Doctor doctors = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.healthcare.doctor_service.service.grpc.Doctor> getDoctorsList() {
    return doctors_;
  }
  /**
   * <code>repeated .Doctor doctors = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.healthcare.doctor_service.service.grpc.DoctorOrBuilder> 
      getDoctorsOrBuilderList() {
    return doctors_;
  }
  /**
   * <code>repeated .Doctor doctors = 1;</code>
   */
  @java.lang.Override
  public int getDoctorsCount() {
    return doctors_.size();
  }
  /**
   * <code>repeated .Doctor doctors = 1;</code>
   */
  @java.lang.Override
  public com.healthcare.doctor_service.service.grpc.Doctor getDoctors(int index) {
    return doctors_.get(index);
  }
  /**
   * <code>repeated .Doctor doctors = 1;</code>
   */
  @java.lang.Override
  public com.healthcare.doctor_service.service.grpc.DoctorOrBuilder getDoctorsOrBuilder(
      int index) {
    return doctors_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < doctors_.size(); i++) {
      output.writeMessage(1, doctors_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < doctors_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, doctors_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.healthcare.doctor_service.service.grpc.DoctorList)) {
      return super.equals(obj);
    }
    com.healthcare.doctor_service.service.grpc.DoctorList other = (com.healthcare.doctor_service.service.grpc.DoctorList) obj;

    if (!getDoctorsList()
        .equals(other.getDoctorsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDoctorsCount() > 0) {
      hash = (37 * hash) + DOCTORS_FIELD_NUMBER;
      hash = (53 * hash) + getDoctorsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.healthcare.doctor_service.service.grpc.DoctorList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.healthcare.doctor_service.service.grpc.DoctorList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.healthcare.doctor_service.service.grpc.DoctorList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.healthcare.doctor_service.service.grpc.DoctorList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.healthcare.doctor_service.service.grpc.DoctorList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.healthcare.doctor_service.service.grpc.DoctorList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.healthcare.doctor_service.service.grpc.DoctorList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.healthcare.doctor_service.service.grpc.DoctorList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.healthcare.doctor_service.service.grpc.DoctorList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.healthcare.doctor_service.service.grpc.DoctorList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.healthcare.doctor_service.service.grpc.DoctorList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.healthcare.doctor_service.service.grpc.DoctorList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.healthcare.doctor_service.service.grpc.DoctorList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DoctorList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DoctorList)
      com.healthcare.doctor_service.service.grpc.DoctorListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.healthcare.doctor_service.service.grpc.DoctorServiceOuterClass.internal_static_DoctorList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.healthcare.doctor_service.service.grpc.DoctorServiceOuterClass.internal_static_DoctorList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.healthcare.doctor_service.service.grpc.DoctorList.class, com.healthcare.doctor_service.service.grpc.DoctorList.Builder.class);
    }

    // Construct using com.healthcare.doctor_service.service.grpc.DoctorList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (doctorsBuilder_ == null) {
        doctors_ = java.util.Collections.emptyList();
      } else {
        doctors_ = null;
        doctorsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.healthcare.doctor_service.service.grpc.DoctorServiceOuterClass.internal_static_DoctorList_descriptor;
    }

    @java.lang.Override
    public com.healthcare.doctor_service.service.grpc.DoctorList getDefaultInstanceForType() {
      return com.healthcare.doctor_service.service.grpc.DoctorList.getDefaultInstance();
    }

    @java.lang.Override
    public com.healthcare.doctor_service.service.grpc.DoctorList build() {
      com.healthcare.doctor_service.service.grpc.DoctorList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.healthcare.doctor_service.service.grpc.DoctorList buildPartial() {
      com.healthcare.doctor_service.service.grpc.DoctorList result = new com.healthcare.doctor_service.service.grpc.DoctorList(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.healthcare.doctor_service.service.grpc.DoctorList result) {
      if (doctorsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          doctors_ = java.util.Collections.unmodifiableList(doctors_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.doctors_ = doctors_;
      } else {
        result.doctors_ = doctorsBuilder_.build();
      }
    }

    private void buildPartial0(com.healthcare.doctor_service.service.grpc.DoctorList result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.healthcare.doctor_service.service.grpc.DoctorList) {
        return mergeFrom((com.healthcare.doctor_service.service.grpc.DoctorList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.healthcare.doctor_service.service.grpc.DoctorList other) {
      if (other == com.healthcare.doctor_service.service.grpc.DoctorList.getDefaultInstance()) return this;
      if (doctorsBuilder_ == null) {
        if (!other.doctors_.isEmpty()) {
          if (doctors_.isEmpty()) {
            doctors_ = other.doctors_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDoctorsIsMutable();
            doctors_.addAll(other.doctors_);
          }
          onChanged();
        }
      } else {
        if (!other.doctors_.isEmpty()) {
          if (doctorsBuilder_.isEmpty()) {
            doctorsBuilder_.dispose();
            doctorsBuilder_ = null;
            doctors_ = other.doctors_;
            bitField0_ = (bitField0_ & ~0x00000001);
            doctorsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDoctorsFieldBuilder() : null;
          } else {
            doctorsBuilder_.addAllMessages(other.doctors_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.healthcare.doctor_service.service.grpc.Doctor m =
                  input.readMessage(
                      com.healthcare.doctor_service.service.grpc.Doctor.parser(),
                      extensionRegistry);
              if (doctorsBuilder_ == null) {
                ensureDoctorsIsMutable();
                doctors_.add(m);
              } else {
                doctorsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.healthcare.doctor_service.service.grpc.Doctor> doctors_ =
      java.util.Collections.emptyList();
    private void ensureDoctorsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        doctors_ = new java.util.ArrayList<com.healthcare.doctor_service.service.grpc.Doctor>(doctors_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.healthcare.doctor_service.service.grpc.Doctor, com.healthcare.doctor_service.service.grpc.Doctor.Builder, com.healthcare.doctor_service.service.grpc.DoctorOrBuilder> doctorsBuilder_;

    /**
     * <code>repeated .Doctor doctors = 1;</code>
     */
    public java.util.List<com.healthcare.doctor_service.service.grpc.Doctor> getDoctorsList() {
      if (doctorsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(doctors_);
      } else {
        return doctorsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Doctor doctors = 1;</code>
     */
    public int getDoctorsCount() {
      if (doctorsBuilder_ == null) {
        return doctors_.size();
      } else {
        return doctorsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Doctor doctors = 1;</code>
     */
    public com.healthcare.doctor_service.service.grpc.Doctor getDoctors(int index) {
      if (doctorsBuilder_ == null) {
        return doctors_.get(index);
      } else {
        return doctorsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Doctor doctors = 1;</code>
     */
    public Builder setDoctors(
        int index, com.healthcare.doctor_service.service.grpc.Doctor value) {
      if (doctorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDoctorsIsMutable();
        doctors_.set(index, value);
        onChanged();
      } else {
        doctorsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Doctor doctors = 1;</code>
     */
    public Builder setDoctors(
        int index, com.healthcare.doctor_service.service.grpc.Doctor.Builder builderForValue) {
      if (doctorsBuilder_ == null) {
        ensureDoctorsIsMutable();
        doctors_.set(index, builderForValue.build());
        onChanged();
      } else {
        doctorsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Doctor doctors = 1;</code>
     */
    public Builder addDoctors(com.healthcare.doctor_service.service.grpc.Doctor value) {
      if (doctorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDoctorsIsMutable();
        doctors_.add(value);
        onChanged();
      } else {
        doctorsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Doctor doctors = 1;</code>
     */
    public Builder addDoctors(
        int index, com.healthcare.doctor_service.service.grpc.Doctor value) {
      if (doctorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDoctorsIsMutable();
        doctors_.add(index, value);
        onChanged();
      } else {
        doctorsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Doctor doctors = 1;</code>
     */
    public Builder addDoctors(
        com.healthcare.doctor_service.service.grpc.Doctor.Builder builderForValue) {
      if (doctorsBuilder_ == null) {
        ensureDoctorsIsMutable();
        doctors_.add(builderForValue.build());
        onChanged();
      } else {
        doctorsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Doctor doctors = 1;</code>
     */
    public Builder addDoctors(
        int index, com.healthcare.doctor_service.service.grpc.Doctor.Builder builderForValue) {
      if (doctorsBuilder_ == null) {
        ensureDoctorsIsMutable();
        doctors_.add(index, builderForValue.build());
        onChanged();
      } else {
        doctorsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Doctor doctors = 1;</code>
     */
    public Builder addAllDoctors(
        java.lang.Iterable<? extends com.healthcare.doctor_service.service.grpc.Doctor> values) {
      if (doctorsBuilder_ == null) {
        ensureDoctorsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, doctors_);
        onChanged();
      } else {
        doctorsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Doctor doctors = 1;</code>
     */
    public Builder clearDoctors() {
      if (doctorsBuilder_ == null) {
        doctors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        doctorsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Doctor doctors = 1;</code>
     */
    public Builder removeDoctors(int index) {
      if (doctorsBuilder_ == null) {
        ensureDoctorsIsMutable();
        doctors_.remove(index);
        onChanged();
      } else {
        doctorsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Doctor doctors = 1;</code>
     */
    public com.healthcare.doctor_service.service.grpc.Doctor.Builder getDoctorsBuilder(
        int index) {
      return getDoctorsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Doctor doctors = 1;</code>
     */
    public com.healthcare.doctor_service.service.grpc.DoctorOrBuilder getDoctorsOrBuilder(
        int index) {
      if (doctorsBuilder_ == null) {
        return doctors_.get(index);  } else {
        return doctorsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Doctor doctors = 1;</code>
     */
    public java.util.List<? extends com.healthcare.doctor_service.service.grpc.DoctorOrBuilder> 
         getDoctorsOrBuilderList() {
      if (doctorsBuilder_ != null) {
        return doctorsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(doctors_);
      }
    }
    /**
     * <code>repeated .Doctor doctors = 1;</code>
     */
    public com.healthcare.doctor_service.service.grpc.Doctor.Builder addDoctorsBuilder() {
      return getDoctorsFieldBuilder().addBuilder(
          com.healthcare.doctor_service.service.grpc.Doctor.getDefaultInstance());
    }
    /**
     * <code>repeated .Doctor doctors = 1;</code>
     */
    public com.healthcare.doctor_service.service.grpc.Doctor.Builder addDoctorsBuilder(
        int index) {
      return getDoctorsFieldBuilder().addBuilder(
          index, com.healthcare.doctor_service.service.grpc.Doctor.getDefaultInstance());
    }
    /**
     * <code>repeated .Doctor doctors = 1;</code>
     */
    public java.util.List<com.healthcare.doctor_service.service.grpc.Doctor.Builder> 
         getDoctorsBuilderList() {
      return getDoctorsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.healthcare.doctor_service.service.grpc.Doctor, com.healthcare.doctor_service.service.grpc.Doctor.Builder, com.healthcare.doctor_service.service.grpc.DoctorOrBuilder> 
        getDoctorsFieldBuilder() {
      if (doctorsBuilder_ == null) {
        doctorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.healthcare.doctor_service.service.grpc.Doctor, com.healthcare.doctor_service.service.grpc.Doctor.Builder, com.healthcare.doctor_service.service.grpc.DoctorOrBuilder>(
                doctors_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        doctors_ = null;
      }
      return doctorsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DoctorList)
  }

  // @@protoc_insertion_point(class_scope:DoctorList)
  private static final com.healthcare.doctor_service.service.grpc.DoctorList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.healthcare.doctor_service.service.grpc.DoctorList();
  }

  public static com.healthcare.doctor_service.service.grpc.DoctorList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DoctorList>
      PARSER = new com.google.protobuf.AbstractParser<DoctorList>() {
    @java.lang.Override
    public DoctorList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DoctorList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DoctorList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.healthcare.doctor_service.service.grpc.DoctorList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

