// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor_service.proto

// Protobuf Java Version: 3.25.3
package com.healthcare.doctor_service.service.grpc;

/**
 * Protobuf type {@code Doctor}
 */
public final class Doctor extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Doctor)
    DoctorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Doctor.newBuilder() to construct.
  private Doctor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Doctor() {
    doctorId_ = "";
    firstName_ = "";
    lastName_ = "";
    specialization_ = "";
    countryCode_ = "";
    phoneNumber_ = "";
    availabilitySlots_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Doctor();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.healthcare.doctor_service.service.grpc.DoctorServiceOuterClass.internal_static_Doctor_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.healthcare.doctor_service.service.grpc.DoctorServiceOuterClass.internal_static_Doctor_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.healthcare.doctor_service.service.grpc.Doctor.class, com.healthcare.doctor_service.service.grpc.Doctor.Builder.class);
  }

  public static final int DOCTOR_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object doctorId_ = "";
  /**
   * <code>string doctor_id = 1;</code>
   * @return The doctorId.
   */
  @java.lang.Override
  public java.lang.String getDoctorId() {
    java.lang.Object ref = doctorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      doctorId_ = s;
      return s;
    }
  }
  /**
   * <code>string doctor_id = 1;</code>
   * @return The bytes for doctorId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDoctorIdBytes() {
    java.lang.Object ref = doctorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      doctorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIRST_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object firstName_ = "";
  /**
   * <code>string first_name = 2;</code>
   * @return The firstName.
   */
  @java.lang.Override
  public java.lang.String getFirstName() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      firstName_ = s;
      return s;
    }
  }
  /**
   * <code>string first_name = 2;</code>
   * @return The bytes for firstName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFirstNameBytes() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      firstName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAST_NAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lastName_ = "";
  /**
   * <code>string last_name = 3;</code>
   * @return The lastName.
   */
  @java.lang.Override
  public java.lang.String getLastName() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastName_ = s;
      return s;
    }
  }
  /**
   * <code>string last_name = 3;</code>
   * @return The bytes for lastName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastNameBytes() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SPECIALIZATION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object specialization_ = "";
  /**
   * <code>string specialization = 4;</code>
   * @return The specialization.
   */
  @java.lang.Override
  public java.lang.String getSpecialization() {
    java.lang.Object ref = specialization_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      specialization_ = s;
      return s;
    }
  }
  /**
   * <code>string specialization = 4;</code>
   * @return The bytes for specialization.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSpecializationBytes() {
    java.lang.Object ref = specialization_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      specialization_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COUNTRY_CODE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object countryCode_ = "";
  /**
   * <code>string country_code = 5;</code>
   * @return The countryCode.
   */
  @java.lang.Override
  public java.lang.String getCountryCode() {
    java.lang.Object ref = countryCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      countryCode_ = s;
      return s;
    }
  }
  /**
   * <code>string country_code = 5;</code>
   * @return The bytes for countryCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCountryCodeBytes() {
    java.lang.Object ref = countryCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      countryCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONE_NUMBER_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object phoneNumber_ = "";
  /**
   * <code>string phone_number = 6;</code>
   * @return The phoneNumber.
   */
  @java.lang.Override
  public java.lang.String getPhoneNumber() {
    java.lang.Object ref = phoneNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      phoneNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string phone_number = 6;</code>
   * @return The bytes for phoneNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhoneNumberBytes() {
    java.lang.Object ref = phoneNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phoneNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVAILABILITY_SLOTS_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private java.util.List<com.healthcare.doctor_service.service.grpc.Slot> availabilitySlots_;
  /**
   * <code>repeated .Slot availability_slots = 7;</code>
   */
  @java.lang.Override
  public java.util.List<com.healthcare.doctor_service.service.grpc.Slot> getAvailabilitySlotsList() {
    return availabilitySlots_;
  }
  /**
   * <code>repeated .Slot availability_slots = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.healthcare.doctor_service.service.grpc.SlotOrBuilder> 
      getAvailabilitySlotsOrBuilderList() {
    return availabilitySlots_;
  }
  /**
   * <code>repeated .Slot availability_slots = 7;</code>
   */
  @java.lang.Override
  public int getAvailabilitySlotsCount() {
    return availabilitySlots_.size();
  }
  /**
   * <code>repeated .Slot availability_slots = 7;</code>
   */
  @java.lang.Override
  public com.healthcare.doctor_service.service.grpc.Slot getAvailabilitySlots(int index) {
    return availabilitySlots_.get(index);
  }
  /**
   * <code>repeated .Slot availability_slots = 7;</code>
   */
  @java.lang.Override
  public com.healthcare.doctor_service.service.grpc.SlotOrBuilder getAvailabilitySlotsOrBuilder(
      int index) {
    return availabilitySlots_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(doctorId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, doctorId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(specialization_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, specialization_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(countryCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, countryCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(phoneNumber_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, phoneNumber_);
    }
    for (int i = 0; i < availabilitySlots_.size(); i++) {
      output.writeMessage(7, availabilitySlots_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(doctorId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, doctorId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(specialization_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, specialization_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(countryCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, countryCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(phoneNumber_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, phoneNumber_);
    }
    for (int i = 0; i < availabilitySlots_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, availabilitySlots_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.healthcare.doctor_service.service.grpc.Doctor)) {
      return super.equals(obj);
    }
    com.healthcare.doctor_service.service.grpc.Doctor other = (com.healthcare.doctor_service.service.grpc.Doctor) obj;

    if (!getDoctorId()
        .equals(other.getDoctorId())) return false;
    if (!getFirstName()
        .equals(other.getFirstName())) return false;
    if (!getLastName()
        .equals(other.getLastName())) return false;
    if (!getSpecialization()
        .equals(other.getSpecialization())) return false;
    if (!getCountryCode()
        .equals(other.getCountryCode())) return false;
    if (!getPhoneNumber()
        .equals(other.getPhoneNumber())) return false;
    if (!getAvailabilitySlotsList()
        .equals(other.getAvailabilitySlotsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DOCTOR_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDoctorId().hashCode();
    hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getFirstName().hashCode();
    hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getLastName().hashCode();
    hash = (37 * hash) + SPECIALIZATION_FIELD_NUMBER;
    hash = (53 * hash) + getSpecialization().hashCode();
    hash = (37 * hash) + COUNTRY_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCountryCode().hashCode();
    hash = (37 * hash) + PHONE_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getPhoneNumber().hashCode();
    if (getAvailabilitySlotsCount() > 0) {
      hash = (37 * hash) + AVAILABILITY_SLOTS_FIELD_NUMBER;
      hash = (53 * hash) + getAvailabilitySlotsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.healthcare.doctor_service.service.grpc.Doctor parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.healthcare.doctor_service.service.grpc.Doctor parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.healthcare.doctor_service.service.grpc.Doctor parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.healthcare.doctor_service.service.grpc.Doctor parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.healthcare.doctor_service.service.grpc.Doctor parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.healthcare.doctor_service.service.grpc.Doctor parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.healthcare.doctor_service.service.grpc.Doctor parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.healthcare.doctor_service.service.grpc.Doctor parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.healthcare.doctor_service.service.grpc.Doctor parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.healthcare.doctor_service.service.grpc.Doctor parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.healthcare.doctor_service.service.grpc.Doctor parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.healthcare.doctor_service.service.grpc.Doctor parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.healthcare.doctor_service.service.grpc.Doctor prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Doctor}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Doctor)
      com.healthcare.doctor_service.service.grpc.DoctorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.healthcare.doctor_service.service.grpc.DoctorServiceOuterClass.internal_static_Doctor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.healthcare.doctor_service.service.grpc.DoctorServiceOuterClass.internal_static_Doctor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.healthcare.doctor_service.service.grpc.Doctor.class, com.healthcare.doctor_service.service.grpc.Doctor.Builder.class);
    }

    // Construct using com.healthcare.doctor_service.service.grpc.Doctor.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      doctorId_ = "";
      firstName_ = "";
      lastName_ = "";
      specialization_ = "";
      countryCode_ = "";
      phoneNumber_ = "";
      if (availabilitySlotsBuilder_ == null) {
        availabilitySlots_ = java.util.Collections.emptyList();
      } else {
        availabilitySlots_ = null;
        availabilitySlotsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.healthcare.doctor_service.service.grpc.DoctorServiceOuterClass.internal_static_Doctor_descriptor;
    }

    @java.lang.Override
    public com.healthcare.doctor_service.service.grpc.Doctor getDefaultInstanceForType() {
      return com.healthcare.doctor_service.service.grpc.Doctor.getDefaultInstance();
    }

    @java.lang.Override
    public com.healthcare.doctor_service.service.grpc.Doctor build() {
      com.healthcare.doctor_service.service.grpc.Doctor result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.healthcare.doctor_service.service.grpc.Doctor buildPartial() {
      com.healthcare.doctor_service.service.grpc.Doctor result = new com.healthcare.doctor_service.service.grpc.Doctor(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.healthcare.doctor_service.service.grpc.Doctor result) {
      if (availabilitySlotsBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)) {
          availabilitySlots_ = java.util.Collections.unmodifiableList(availabilitySlots_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.availabilitySlots_ = availabilitySlots_;
      } else {
        result.availabilitySlots_ = availabilitySlotsBuilder_.build();
      }
    }

    private void buildPartial0(com.healthcare.doctor_service.service.grpc.Doctor result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.doctorId_ = doctorId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.firstName_ = firstName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.lastName_ = lastName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.specialization_ = specialization_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.countryCode_ = countryCode_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.phoneNumber_ = phoneNumber_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.healthcare.doctor_service.service.grpc.Doctor) {
        return mergeFrom((com.healthcare.doctor_service.service.grpc.Doctor)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.healthcare.doctor_service.service.grpc.Doctor other) {
      if (other == com.healthcare.doctor_service.service.grpc.Doctor.getDefaultInstance()) return this;
      if (!other.getDoctorId().isEmpty()) {
        doctorId_ = other.doctorId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getFirstName().isEmpty()) {
        firstName_ = other.firstName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getLastName().isEmpty()) {
        lastName_ = other.lastName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getSpecialization().isEmpty()) {
        specialization_ = other.specialization_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getCountryCode().isEmpty()) {
        countryCode_ = other.countryCode_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getPhoneNumber().isEmpty()) {
        phoneNumber_ = other.phoneNumber_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (availabilitySlotsBuilder_ == null) {
        if (!other.availabilitySlots_.isEmpty()) {
          if (availabilitySlots_.isEmpty()) {
            availabilitySlots_ = other.availabilitySlots_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureAvailabilitySlotsIsMutable();
            availabilitySlots_.addAll(other.availabilitySlots_);
          }
          onChanged();
        }
      } else {
        if (!other.availabilitySlots_.isEmpty()) {
          if (availabilitySlotsBuilder_.isEmpty()) {
            availabilitySlotsBuilder_.dispose();
            availabilitySlotsBuilder_ = null;
            availabilitySlots_ = other.availabilitySlots_;
            bitField0_ = (bitField0_ & ~0x00000040);
            availabilitySlotsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAvailabilitySlotsFieldBuilder() : null;
          } else {
            availabilitySlotsBuilder_.addAllMessages(other.availabilitySlots_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              doctorId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              firstName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              lastName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              specialization_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              countryCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              phoneNumber_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              com.healthcare.doctor_service.service.grpc.Slot m =
                  input.readMessage(
                      com.healthcare.doctor_service.service.grpc.Slot.parser(),
                      extensionRegistry);
              if (availabilitySlotsBuilder_ == null) {
                ensureAvailabilitySlotsIsMutable();
                availabilitySlots_.add(m);
              } else {
                availabilitySlotsBuilder_.addMessage(m);
              }
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object doctorId_ = "";
    /**
     * <code>string doctor_id = 1;</code>
     * @return The doctorId.
     */
    public java.lang.String getDoctorId() {
      java.lang.Object ref = doctorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        doctorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string doctor_id = 1;</code>
     * @return The bytes for doctorId.
     */
    public com.google.protobuf.ByteString
        getDoctorIdBytes() {
      java.lang.Object ref = doctorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        doctorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string doctor_id = 1;</code>
     * @param value The doctorId to set.
     * @return This builder for chaining.
     */
    public Builder setDoctorId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      doctorId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string doctor_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDoctorId() {
      doctorId_ = getDefaultInstance().getDoctorId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string doctor_id = 1;</code>
     * @param value The bytes for doctorId to set.
     * @return This builder for chaining.
     */
    public Builder setDoctorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      doctorId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object firstName_ = "";
    /**
     * <code>string first_name = 2;</code>
     * @return The firstName.
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string first_name = 2;</code>
     * @return The bytes for firstName.
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string first_name = 2;</code>
     * @param value The firstName to set.
     * @return This builder for chaining.
     */
    public Builder setFirstName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      firstName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string first_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFirstName() {
      firstName_ = getDefaultInstance().getFirstName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string first_name = 2;</code>
     * @param value The bytes for firstName to set.
     * @return This builder for chaining.
     */
    public Builder setFirstNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      firstName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object lastName_ = "";
    /**
     * <code>string last_name = 3;</code>
     * @return The lastName.
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string last_name = 3;</code>
     * @return The bytes for lastName.
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string last_name = 3;</code>
     * @param value The lastName to set.
     * @return This builder for chaining.
     */
    public Builder setLastName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lastName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string last_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastName() {
      lastName_ = getDefaultInstance().getLastName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string last_name = 3;</code>
     * @param value The bytes for lastName to set.
     * @return This builder for chaining.
     */
    public Builder setLastNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lastName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object specialization_ = "";
    /**
     * <code>string specialization = 4;</code>
     * @return The specialization.
     */
    public java.lang.String getSpecialization() {
      java.lang.Object ref = specialization_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        specialization_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string specialization = 4;</code>
     * @return The bytes for specialization.
     */
    public com.google.protobuf.ByteString
        getSpecializationBytes() {
      java.lang.Object ref = specialization_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        specialization_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string specialization = 4;</code>
     * @param value The specialization to set.
     * @return This builder for chaining.
     */
    public Builder setSpecialization(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      specialization_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string specialization = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpecialization() {
      specialization_ = getDefaultInstance().getSpecialization();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string specialization = 4;</code>
     * @param value The bytes for specialization to set.
     * @return This builder for chaining.
     */
    public Builder setSpecializationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      specialization_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object countryCode_ = "";
    /**
     * <code>string country_code = 5;</code>
     * @return The countryCode.
     */
    public java.lang.String getCountryCode() {
      java.lang.Object ref = countryCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        countryCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string country_code = 5;</code>
     * @return The bytes for countryCode.
     */
    public com.google.protobuf.ByteString
        getCountryCodeBytes() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string country_code = 5;</code>
     * @param value The countryCode to set.
     * @return This builder for chaining.
     */
    public Builder setCountryCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      countryCode_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string country_code = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCountryCode() {
      countryCode_ = getDefaultInstance().getCountryCode();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string country_code = 5;</code>
     * @param value The bytes for countryCode to set.
     * @return This builder for chaining.
     */
    public Builder setCountryCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      countryCode_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object phoneNumber_ = "";
    /**
     * <code>string phone_number = 6;</code>
     * @return The phoneNumber.
     */
    public java.lang.String getPhoneNumber() {
      java.lang.Object ref = phoneNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string phone_number = 6;</code>
     * @return The bytes for phoneNumber.
     */
    public com.google.protobuf.ByteString
        getPhoneNumberBytes() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string phone_number = 6;</code>
     * @param value The phoneNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPhoneNumber(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      phoneNumber_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string phone_number = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhoneNumber() {
      phoneNumber_ = getDefaultInstance().getPhoneNumber();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string phone_number = 6;</code>
     * @param value The bytes for phoneNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPhoneNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      phoneNumber_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.util.List<com.healthcare.doctor_service.service.grpc.Slot> availabilitySlots_ =
      java.util.Collections.emptyList();
    private void ensureAvailabilitySlotsIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        availabilitySlots_ = new java.util.ArrayList<com.healthcare.doctor_service.service.grpc.Slot>(availabilitySlots_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.healthcare.doctor_service.service.grpc.Slot, com.healthcare.doctor_service.service.grpc.Slot.Builder, com.healthcare.doctor_service.service.grpc.SlotOrBuilder> availabilitySlotsBuilder_;

    /**
     * <code>repeated .Slot availability_slots = 7;</code>
     */
    public java.util.List<com.healthcare.doctor_service.service.grpc.Slot> getAvailabilitySlotsList() {
      if (availabilitySlotsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(availabilitySlots_);
      } else {
        return availabilitySlotsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Slot availability_slots = 7;</code>
     */
    public int getAvailabilitySlotsCount() {
      if (availabilitySlotsBuilder_ == null) {
        return availabilitySlots_.size();
      } else {
        return availabilitySlotsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Slot availability_slots = 7;</code>
     */
    public com.healthcare.doctor_service.service.grpc.Slot getAvailabilitySlots(int index) {
      if (availabilitySlotsBuilder_ == null) {
        return availabilitySlots_.get(index);
      } else {
        return availabilitySlotsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Slot availability_slots = 7;</code>
     */
    public Builder setAvailabilitySlots(
        int index, com.healthcare.doctor_service.service.grpc.Slot value) {
      if (availabilitySlotsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAvailabilitySlotsIsMutable();
        availabilitySlots_.set(index, value);
        onChanged();
      } else {
        availabilitySlotsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Slot availability_slots = 7;</code>
     */
    public Builder setAvailabilitySlots(
        int index, com.healthcare.doctor_service.service.grpc.Slot.Builder builderForValue) {
      if (availabilitySlotsBuilder_ == null) {
        ensureAvailabilitySlotsIsMutable();
        availabilitySlots_.set(index, builderForValue.build());
        onChanged();
      } else {
        availabilitySlotsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Slot availability_slots = 7;</code>
     */
    public Builder addAvailabilitySlots(com.healthcare.doctor_service.service.grpc.Slot value) {
      if (availabilitySlotsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAvailabilitySlotsIsMutable();
        availabilitySlots_.add(value);
        onChanged();
      } else {
        availabilitySlotsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Slot availability_slots = 7;</code>
     */
    public Builder addAvailabilitySlots(
        int index, com.healthcare.doctor_service.service.grpc.Slot value) {
      if (availabilitySlotsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAvailabilitySlotsIsMutable();
        availabilitySlots_.add(index, value);
        onChanged();
      } else {
        availabilitySlotsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Slot availability_slots = 7;</code>
     */
    public Builder addAvailabilitySlots(
        com.healthcare.doctor_service.service.grpc.Slot.Builder builderForValue) {
      if (availabilitySlotsBuilder_ == null) {
        ensureAvailabilitySlotsIsMutable();
        availabilitySlots_.add(builderForValue.build());
        onChanged();
      } else {
        availabilitySlotsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Slot availability_slots = 7;</code>
     */
    public Builder addAvailabilitySlots(
        int index, com.healthcare.doctor_service.service.grpc.Slot.Builder builderForValue) {
      if (availabilitySlotsBuilder_ == null) {
        ensureAvailabilitySlotsIsMutable();
        availabilitySlots_.add(index, builderForValue.build());
        onChanged();
      } else {
        availabilitySlotsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Slot availability_slots = 7;</code>
     */
    public Builder addAllAvailabilitySlots(
        java.lang.Iterable<? extends com.healthcare.doctor_service.service.grpc.Slot> values) {
      if (availabilitySlotsBuilder_ == null) {
        ensureAvailabilitySlotsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, availabilitySlots_);
        onChanged();
      } else {
        availabilitySlotsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Slot availability_slots = 7;</code>
     */
    public Builder clearAvailabilitySlots() {
      if (availabilitySlotsBuilder_ == null) {
        availabilitySlots_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        availabilitySlotsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Slot availability_slots = 7;</code>
     */
    public Builder removeAvailabilitySlots(int index) {
      if (availabilitySlotsBuilder_ == null) {
        ensureAvailabilitySlotsIsMutable();
        availabilitySlots_.remove(index);
        onChanged();
      } else {
        availabilitySlotsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Slot availability_slots = 7;</code>
     */
    public com.healthcare.doctor_service.service.grpc.Slot.Builder getAvailabilitySlotsBuilder(
        int index) {
      return getAvailabilitySlotsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Slot availability_slots = 7;</code>
     */
    public com.healthcare.doctor_service.service.grpc.SlotOrBuilder getAvailabilitySlotsOrBuilder(
        int index) {
      if (availabilitySlotsBuilder_ == null) {
        return availabilitySlots_.get(index);  } else {
        return availabilitySlotsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Slot availability_slots = 7;</code>
     */
    public java.util.List<? extends com.healthcare.doctor_service.service.grpc.SlotOrBuilder> 
         getAvailabilitySlotsOrBuilderList() {
      if (availabilitySlotsBuilder_ != null) {
        return availabilitySlotsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(availabilitySlots_);
      }
    }
    /**
     * <code>repeated .Slot availability_slots = 7;</code>
     */
    public com.healthcare.doctor_service.service.grpc.Slot.Builder addAvailabilitySlotsBuilder() {
      return getAvailabilitySlotsFieldBuilder().addBuilder(
          com.healthcare.doctor_service.service.grpc.Slot.getDefaultInstance());
    }
    /**
     * <code>repeated .Slot availability_slots = 7;</code>
     */
    public com.healthcare.doctor_service.service.grpc.Slot.Builder addAvailabilitySlotsBuilder(
        int index) {
      return getAvailabilitySlotsFieldBuilder().addBuilder(
          index, com.healthcare.doctor_service.service.grpc.Slot.getDefaultInstance());
    }
    /**
     * <code>repeated .Slot availability_slots = 7;</code>
     */
    public java.util.List<com.healthcare.doctor_service.service.grpc.Slot.Builder> 
         getAvailabilitySlotsBuilderList() {
      return getAvailabilitySlotsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.healthcare.doctor_service.service.grpc.Slot, com.healthcare.doctor_service.service.grpc.Slot.Builder, com.healthcare.doctor_service.service.grpc.SlotOrBuilder> 
        getAvailabilitySlotsFieldBuilder() {
      if (availabilitySlotsBuilder_ == null) {
        availabilitySlotsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.healthcare.doctor_service.service.grpc.Slot, com.healthcare.doctor_service.service.grpc.Slot.Builder, com.healthcare.doctor_service.service.grpc.SlotOrBuilder>(
                availabilitySlots_,
                ((bitField0_ & 0x00000040) != 0),
                getParentForChildren(),
                isClean());
        availabilitySlots_ = null;
      }
      return availabilitySlotsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Doctor)
  }

  // @@protoc_insertion_point(class_scope:Doctor)
  private static final com.healthcare.doctor_service.service.grpc.Doctor DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.healthcare.doctor_service.service.grpc.Doctor();
  }

  public static com.healthcare.doctor_service.service.grpc.Doctor getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Doctor>
      PARSER = new com.google.protobuf.AbstractParser<Doctor>() {
    @java.lang.Override
    public Doctor parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Doctor> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Doctor> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.healthcare.doctor_service.service.grpc.Doctor getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

