// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor_service.proto

// Protobuf Java Version: 3.25.3
package com.healthcare.doctor_service.service.grpc;

public interface GetAvailabilityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAvailabilityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string doctor_id = 1;</code>
   * @return The doctorId.
   */
  java.lang.String getDoctorId();
  /**
   * <code>string doctor_id = 1;</code>
   * @return The bytes for doctorId.
   */
  com.google.protobuf.ByteString
      getDoctorIdBytes();
}
