// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor_service.proto

// Protobuf Java Version: 3.25.3
package com.healthcare.doctor_service.service.grpc;

/**
 * Protobuf type {@code SlotList}
 */
public final class SlotList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SlotList)
    SlotListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SlotList.newBuilder() to construct.
  private SlotList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SlotList() {
    slots_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SlotList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.healthcare.doctor_service.service.grpc.DoctorServiceOuterClass.internal_static_SlotList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.healthcare.doctor_service.service.grpc.DoctorServiceOuterClass.internal_static_SlotList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.healthcare.doctor_service.service.grpc.SlotList.class, com.healthcare.doctor_service.service.grpc.SlotList.Builder.class);
  }

  public static final int SLOTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.healthcare.doctor_service.service.grpc.Slot> slots_;
  /**
   * <code>repeated .Slot slots = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.healthcare.doctor_service.service.grpc.Slot> getSlotsList() {
    return slots_;
  }
  /**
   * <code>repeated .Slot slots = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.healthcare.doctor_service.service.grpc.SlotOrBuilder> 
      getSlotsOrBuilderList() {
    return slots_;
  }
  /**
   * <code>repeated .Slot slots = 1;</code>
   */
  @java.lang.Override
  public int getSlotsCount() {
    return slots_.size();
  }
  /**
   * <code>repeated .Slot slots = 1;</code>
   */
  @java.lang.Override
  public com.healthcare.doctor_service.service.grpc.Slot getSlots(int index) {
    return slots_.get(index);
  }
  /**
   * <code>repeated .Slot slots = 1;</code>
   */
  @java.lang.Override
  public com.healthcare.doctor_service.service.grpc.SlotOrBuilder getSlotsOrBuilder(
      int index) {
    return slots_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < slots_.size(); i++) {
      output.writeMessage(1, slots_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < slots_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, slots_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.healthcare.doctor_service.service.grpc.SlotList)) {
      return super.equals(obj);
    }
    com.healthcare.doctor_service.service.grpc.SlotList other = (com.healthcare.doctor_service.service.grpc.SlotList) obj;

    if (!getSlotsList()
        .equals(other.getSlotsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSlotsCount() > 0) {
      hash = (37 * hash) + SLOTS_FIELD_NUMBER;
      hash = (53 * hash) + getSlotsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.healthcare.doctor_service.service.grpc.SlotList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.healthcare.doctor_service.service.grpc.SlotList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.healthcare.doctor_service.service.grpc.SlotList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.healthcare.doctor_service.service.grpc.SlotList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.healthcare.doctor_service.service.grpc.SlotList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.healthcare.doctor_service.service.grpc.SlotList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.healthcare.doctor_service.service.grpc.SlotList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.healthcare.doctor_service.service.grpc.SlotList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.healthcare.doctor_service.service.grpc.SlotList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.healthcare.doctor_service.service.grpc.SlotList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.healthcare.doctor_service.service.grpc.SlotList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.healthcare.doctor_service.service.grpc.SlotList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.healthcare.doctor_service.service.grpc.SlotList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SlotList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SlotList)
      com.healthcare.doctor_service.service.grpc.SlotListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.healthcare.doctor_service.service.grpc.DoctorServiceOuterClass.internal_static_SlotList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.healthcare.doctor_service.service.grpc.DoctorServiceOuterClass.internal_static_SlotList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.healthcare.doctor_service.service.grpc.SlotList.class, com.healthcare.doctor_service.service.grpc.SlotList.Builder.class);
    }

    // Construct using com.healthcare.doctor_service.service.grpc.SlotList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (slotsBuilder_ == null) {
        slots_ = java.util.Collections.emptyList();
      } else {
        slots_ = null;
        slotsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.healthcare.doctor_service.service.grpc.DoctorServiceOuterClass.internal_static_SlotList_descriptor;
    }

    @java.lang.Override
    public com.healthcare.doctor_service.service.grpc.SlotList getDefaultInstanceForType() {
      return com.healthcare.doctor_service.service.grpc.SlotList.getDefaultInstance();
    }

    @java.lang.Override
    public com.healthcare.doctor_service.service.grpc.SlotList build() {
      com.healthcare.doctor_service.service.grpc.SlotList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.healthcare.doctor_service.service.grpc.SlotList buildPartial() {
      com.healthcare.doctor_service.service.grpc.SlotList result = new com.healthcare.doctor_service.service.grpc.SlotList(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.healthcare.doctor_service.service.grpc.SlotList result) {
      if (slotsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          slots_ = java.util.Collections.unmodifiableList(slots_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.slots_ = slots_;
      } else {
        result.slots_ = slotsBuilder_.build();
      }
    }

    private void buildPartial0(com.healthcare.doctor_service.service.grpc.SlotList result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.healthcare.doctor_service.service.grpc.SlotList) {
        return mergeFrom((com.healthcare.doctor_service.service.grpc.SlotList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.healthcare.doctor_service.service.grpc.SlotList other) {
      if (other == com.healthcare.doctor_service.service.grpc.SlotList.getDefaultInstance()) return this;
      if (slotsBuilder_ == null) {
        if (!other.slots_.isEmpty()) {
          if (slots_.isEmpty()) {
            slots_ = other.slots_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSlotsIsMutable();
            slots_.addAll(other.slots_);
          }
          onChanged();
        }
      } else {
        if (!other.slots_.isEmpty()) {
          if (slotsBuilder_.isEmpty()) {
            slotsBuilder_.dispose();
            slotsBuilder_ = null;
            slots_ = other.slots_;
            bitField0_ = (bitField0_ & ~0x00000001);
            slotsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSlotsFieldBuilder() : null;
          } else {
            slotsBuilder_.addAllMessages(other.slots_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.healthcare.doctor_service.service.grpc.Slot m =
                  input.readMessage(
                      com.healthcare.doctor_service.service.grpc.Slot.parser(),
                      extensionRegistry);
              if (slotsBuilder_ == null) {
                ensureSlotsIsMutable();
                slots_.add(m);
              } else {
                slotsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.healthcare.doctor_service.service.grpc.Slot> slots_ =
      java.util.Collections.emptyList();
    private void ensureSlotsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        slots_ = new java.util.ArrayList<com.healthcare.doctor_service.service.grpc.Slot>(slots_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.healthcare.doctor_service.service.grpc.Slot, com.healthcare.doctor_service.service.grpc.Slot.Builder, com.healthcare.doctor_service.service.grpc.SlotOrBuilder> slotsBuilder_;

    /**
     * <code>repeated .Slot slots = 1;</code>
     */
    public java.util.List<com.healthcare.doctor_service.service.grpc.Slot> getSlotsList() {
      if (slotsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(slots_);
      } else {
        return slotsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Slot slots = 1;</code>
     */
    public int getSlotsCount() {
      if (slotsBuilder_ == null) {
        return slots_.size();
      } else {
        return slotsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Slot slots = 1;</code>
     */
    public com.healthcare.doctor_service.service.grpc.Slot getSlots(int index) {
      if (slotsBuilder_ == null) {
        return slots_.get(index);
      } else {
        return slotsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Slot slots = 1;</code>
     */
    public Builder setSlots(
        int index, com.healthcare.doctor_service.service.grpc.Slot value) {
      if (slotsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSlotsIsMutable();
        slots_.set(index, value);
        onChanged();
      } else {
        slotsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Slot slots = 1;</code>
     */
    public Builder setSlots(
        int index, com.healthcare.doctor_service.service.grpc.Slot.Builder builderForValue) {
      if (slotsBuilder_ == null) {
        ensureSlotsIsMutable();
        slots_.set(index, builderForValue.build());
        onChanged();
      } else {
        slotsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Slot slots = 1;</code>
     */
    public Builder addSlots(com.healthcare.doctor_service.service.grpc.Slot value) {
      if (slotsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSlotsIsMutable();
        slots_.add(value);
        onChanged();
      } else {
        slotsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Slot slots = 1;</code>
     */
    public Builder addSlots(
        int index, com.healthcare.doctor_service.service.grpc.Slot value) {
      if (slotsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSlotsIsMutable();
        slots_.add(index, value);
        onChanged();
      } else {
        slotsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Slot slots = 1;</code>
     */
    public Builder addSlots(
        com.healthcare.doctor_service.service.grpc.Slot.Builder builderForValue) {
      if (slotsBuilder_ == null) {
        ensureSlotsIsMutable();
        slots_.add(builderForValue.build());
        onChanged();
      } else {
        slotsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Slot slots = 1;</code>
     */
    public Builder addSlots(
        int index, com.healthcare.doctor_service.service.grpc.Slot.Builder builderForValue) {
      if (slotsBuilder_ == null) {
        ensureSlotsIsMutable();
        slots_.add(index, builderForValue.build());
        onChanged();
      } else {
        slotsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Slot slots = 1;</code>
     */
    public Builder addAllSlots(
        java.lang.Iterable<? extends com.healthcare.doctor_service.service.grpc.Slot> values) {
      if (slotsBuilder_ == null) {
        ensureSlotsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, slots_);
        onChanged();
      } else {
        slotsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Slot slots = 1;</code>
     */
    public Builder clearSlots() {
      if (slotsBuilder_ == null) {
        slots_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        slotsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Slot slots = 1;</code>
     */
    public Builder removeSlots(int index) {
      if (slotsBuilder_ == null) {
        ensureSlotsIsMutable();
        slots_.remove(index);
        onChanged();
      } else {
        slotsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Slot slots = 1;</code>
     */
    public com.healthcare.doctor_service.service.grpc.Slot.Builder getSlotsBuilder(
        int index) {
      return getSlotsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Slot slots = 1;</code>
     */
    public com.healthcare.doctor_service.service.grpc.SlotOrBuilder getSlotsOrBuilder(
        int index) {
      if (slotsBuilder_ == null) {
        return slots_.get(index);  } else {
        return slotsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Slot slots = 1;</code>
     */
    public java.util.List<? extends com.healthcare.doctor_service.service.grpc.SlotOrBuilder> 
         getSlotsOrBuilderList() {
      if (slotsBuilder_ != null) {
        return slotsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(slots_);
      }
    }
    /**
     * <code>repeated .Slot slots = 1;</code>
     */
    public com.healthcare.doctor_service.service.grpc.Slot.Builder addSlotsBuilder() {
      return getSlotsFieldBuilder().addBuilder(
          com.healthcare.doctor_service.service.grpc.Slot.getDefaultInstance());
    }
    /**
     * <code>repeated .Slot slots = 1;</code>
     */
    public com.healthcare.doctor_service.service.grpc.Slot.Builder addSlotsBuilder(
        int index) {
      return getSlotsFieldBuilder().addBuilder(
          index, com.healthcare.doctor_service.service.grpc.Slot.getDefaultInstance());
    }
    /**
     * <code>repeated .Slot slots = 1;</code>
     */
    public java.util.List<com.healthcare.doctor_service.service.grpc.Slot.Builder> 
         getSlotsBuilderList() {
      return getSlotsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.healthcare.doctor_service.service.grpc.Slot, com.healthcare.doctor_service.service.grpc.Slot.Builder, com.healthcare.doctor_service.service.grpc.SlotOrBuilder> 
        getSlotsFieldBuilder() {
      if (slotsBuilder_ == null) {
        slotsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.healthcare.doctor_service.service.grpc.Slot, com.healthcare.doctor_service.service.grpc.Slot.Builder, com.healthcare.doctor_service.service.grpc.SlotOrBuilder>(
                slots_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        slots_ = null;
      }
      return slotsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SlotList)
  }

  // @@protoc_insertion_point(class_scope:SlotList)
  private static final com.healthcare.doctor_service.service.grpc.SlotList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.healthcare.doctor_service.service.grpc.SlotList();
  }

  public static com.healthcare.doctor_service.service.grpc.SlotList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SlotList>
      PARSER = new com.google.protobuf.AbstractParser<SlotList>() {
    @java.lang.Override
    public SlotList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SlotList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SlotList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.healthcare.doctor_service.service.grpc.SlotList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

