// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor_service.proto

// Protobuf Java Version: 3.25.3
package com.healthcare.doctor_service.service.grpc;

public interface SlotListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SlotList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Slot slots = 1;</code>
   */
  java.util.List<com.healthcare.doctor_service.service.grpc.Slot> 
      getSlotsList();
  /**
   * <code>repeated .Slot slots = 1;</code>
   */
  com.healthcare.doctor_service.service.grpc.Slot getSlots(int index);
  /**
   * <code>repeated .Slot slots = 1;</code>
   */
  int getSlotsCount();
  /**
   * <code>repeated .Slot slots = 1;</code>
   */
  java.util.List<? extends com.healthcare.doctor_service.service.grpc.SlotOrBuilder> 
      getSlotsOrBuilderList();
  /**
   * <code>repeated .Slot slots = 1;</code>
   */
  com.healthcare.doctor_service.service.grpc.SlotOrBuilder getSlotsOrBuilder(
      int index);
}
