// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor_service.proto

// Protobuf Java Version: 3.25.3
package com.healthcare.api_gateway.service.grpc;

public interface BookSlotResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BookSlotResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool exist = 1;</code>
   * @return The exist.
   */
  boolean getExist();
}
