// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor_service.proto

// Protobuf Java Version: 3.25.3
package com.healthcare.api_gateway.service.grpc;

public interface BookSlotRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BookSlotRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 slot_id = 1;</code>
   * @return The slotId.
   */
  long getSlotId();
}
