// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor_service.proto

// Protobuf Java Version: 3.25.3
package com.healthcare.api_gateway.service.grpc;

public interface CreateDoctorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateDoctorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string doctor_id = 1;</code>
   * @return The doctorId.
   */
  java.lang.String getDoctorId();
  /**
   * <code>string doctor_id = 1;</code>
   * @return The bytes for doctorId.
   */
  com.google.protobuf.ByteString
      getDoctorIdBytes();

  /**
   * <code>string full_name = 2;</code>
   * @return The fullName.
   */
  java.lang.String getFullName();
  /**
   * <code>string full_name = 2;</code>
   * @return The bytes for fullName.
   */
  com.google.protobuf.ByteString
      getFullNameBytes();

  /**
   * <code>string specialization = 3;</code>
   * @return The specialization.
   */
  java.lang.String getSpecialization();
  /**
   * <code>string specialization = 3;</code>
   * @return The bytes for specialization.
   */
  com.google.protobuf.ByteString
      getSpecializationBytes();

  /**
   * <code>string phone_number = 4;</code>
   * @return The phoneNumber.
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>string phone_number = 4;</code>
   * @return The bytes for phoneNumber.
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();
}
