// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor_service.proto

// Protobuf Java Version: 3.25.3
package com.healthcare.api_gateway.service.grpc;

public interface DoctorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Doctor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string doctor_id = 1;</code>
   * @return The doctorId.
   */
  java.lang.String getDoctorId();
  /**
   * <code>string doctor_id = 1;</code>
   * @return The bytes for doctorId.
   */
  com.google.protobuf.ByteString
      getDoctorIdBytes();

  /**
   * <code>string first_name = 2;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 2;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_name = 3;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 3;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string specialization = 4;</code>
   * @return The specialization.
   */
  java.lang.String getSpecialization();
  /**
   * <code>string specialization = 4;</code>
   * @return The bytes for specialization.
   */
  com.google.protobuf.ByteString
      getSpecializationBytes();

  /**
   * <code>string country_code = 5;</code>
   * @return The countryCode.
   */
  java.lang.String getCountryCode();
  /**
   * <code>string country_code = 5;</code>
   * @return The bytes for countryCode.
   */
  com.google.protobuf.ByteString
      getCountryCodeBytes();

  /**
   * <code>string phone_number = 6;</code>
   * @return The phoneNumber.
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>string phone_number = 6;</code>
   * @return The bytes for phoneNumber.
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();

  /**
   * <code>repeated .Slot availability_slots = 7;</code>
   */
  java.util.List<com.healthcare.api_gateway.service.grpc.Slot> 
      getAvailabilitySlotsList();
  /**
   * <code>repeated .Slot availability_slots = 7;</code>
   */
  com.healthcare.api_gateway.service.grpc.Slot getAvailabilitySlots(int index);
  /**
   * <code>repeated .Slot availability_slots = 7;</code>
   */
  int getAvailabilitySlotsCount();
  /**
   * <code>repeated .Slot availability_slots = 7;</code>
   */
  java.util.List<? extends com.healthcare.api_gateway.service.grpc.SlotOrBuilder> 
      getAvailabilitySlotsOrBuilderList();
  /**
   * <code>repeated .Slot availability_slots = 7;</code>
   */
  com.healthcare.api_gateway.service.grpc.SlotOrBuilder getAvailabilitySlotsOrBuilder(
      int index);
}
