// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor_service.proto

// Protobuf Java Version: 3.25.3
package com.healthcare.api_gateway.service.grpc;

public final class DoctorServiceOuterClass {
  private DoctorServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookSlotResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookSlotResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookSlotRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookSlotRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAvailabilityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAvailabilityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddAvailabilityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddAvailabilityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddAvailabilityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddAvailabilityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Specialization_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Specialization_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateDoctorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateDoctorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateDoctorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateDoctorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Doctor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Doctor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Slot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Slot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DoctorList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DoctorList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SlotList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SlotList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024doctor_service.proto\032\036google/protobuf/" +
      "duration.proto\032\037google/protobuf/timestam" +
      "p.proto\"\007\n\005Empty\"!\n\020BookSlotResponse\022\r\n\005" +
      "exist\030\001 \001(\010\"\"\n\017BookSlotRequest\022\017\n\007slot_i" +
      "d\030\001 \001(\003\"+\n\026GetAvailabilityRequest\022\021\n\tdoc" +
      "tor_id\030\001 \001(\t\"\210\001\n\026AddAvailabilityRequest\022" +
      "\021\n\tdoctor_id\030\001 \001(\t\022.\n\nstart_time\030\002 \001(\0132\032" +
      ".google.protobuf.Timestamp\022+\n\010duration\030\003" +
      " \001(\0132\031.google.protobuf.Duration\"\210\001\n\027AddA" +
      "vailabilityResponse\022\017\n\007slot_id\030\001 \001(\003\022.\n\n" +
      "start_time\030\002 \001(\0132\032.google.protobuf.Times" +
      "tamp\022,\n\010end_time\030\003 \001(\0132\032.google.protobuf" +
      ".Timestamp\"(\n\016Specialization\022\026\n\016speciali" +
      "zation\030\001 \001(\t\"\200\001\n\023CreateDoctorRequest\022\022\n\n" +
      "first_name\030\001 \001(\t\022\021\n\tlast_name\030\002 \001(\t\022\026\n\016s" +
      "pecialization\030\003 \001(\t\022\024\n\014country_code\030\004 \001(" +
      "\t\022\024\n\014phone_number\030\005 \001(\t\"j\n\024CreateDoctorR" +
      "esponse\022\021\n\tdoctor_id\030\001 \001(\t\022\021\n\tfull_name\030" +
      "\002 \001(\t\022\026\n\016specialization\030\003 \001(\t\022\024\n\014phone_n" +
      "umber\030\004 \001(\t\"\251\001\n\006Doctor\022\021\n\tdoctor_id\030\001 \001(" +
      "\t\022\022\n\nfirst_name\030\002 \001(\t\022\021\n\tlast_name\030\003 \001(\t" +
      "\022\026\n\016specialization\030\004 \001(\t\022\024\n\014country_code" +
      "\030\005 \001(\t\022\024\n\014phone_number\030\006 \001(\t\022!\n\022availabi" +
      "lity_slots\030\007 \003(\0132\005.Slot\"\230\001\n\004Slot\022\017\n\007slot" +
      "_id\030\001 \001(\003\022\021\n\tdoctor_id\030\002 \001(\t\022.\n\nstart_ti" +
      "me\030\003 \001(\0132\032.google.protobuf.Timestamp\022,\n\010" +
      "end_time\030\004 \001(\0132\032.google.protobuf.Timesta" +
      "mp\022\016\n\006booked\030\005 \001(\010\"&\n\nDoctorList\022\030\n\007doct" +
      "ors\030\001 \003(\0132\007.Doctor\" \n\010SlotList\022\024\n\005slots\030" +
      "\001 \003(\0132\005.Slot2\253\001\n\rDoctorService\022;\n\014Create" +
      "Doctor\022\024.CreateDoctorRequest\032\025.CreateDoc" +
      "torResponse\022!\n\nGetDoctors\022\006.Empty\032\013.Doct" +
      "orList\022:\n\032GetDoctorsBySpecialization\022\017.S" +
      "pecialization\032\013.DoctorList2\300\001\n\020Available" +
      "Service\022D\n\017AddAvailability\022\027.AddAvailabi" +
      "lityRequest\032\030.AddAvailabilityResponse\0225\n" +
      "\017GetAvailability\022\027.GetAvailabilityReques" +
      "t\032\t.SlotList\022/\n\010BookSlot\022\020.BookSlotReque" +
      "st\032\021.BookSlotResponseB+\n\'com.healthcare." +
      "api_gateway.service.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_BookSlotResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BookSlotResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookSlotResponse_descriptor,
        new java.lang.String[] { "Exist", });
    internal_static_BookSlotRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BookSlotRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookSlotRequest_descriptor,
        new java.lang.String[] { "SlotId", });
    internal_static_GetAvailabilityRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetAvailabilityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAvailabilityRequest_descriptor,
        new java.lang.String[] { "DoctorId", });
    internal_static_AddAvailabilityRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_AddAvailabilityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddAvailabilityRequest_descriptor,
        new java.lang.String[] { "DoctorId", "StartTime", "Duration", });
    internal_static_AddAvailabilityResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_AddAvailabilityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddAvailabilityResponse_descriptor,
        new java.lang.String[] { "SlotId", "StartTime", "EndTime", });
    internal_static_Specialization_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Specialization_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Specialization_descriptor,
        new java.lang.String[] { "Specialization", });
    internal_static_CreateDoctorRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_CreateDoctorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateDoctorRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Specialization", "CountryCode", "PhoneNumber", });
    internal_static_CreateDoctorResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_CreateDoctorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateDoctorResponse_descriptor,
        new java.lang.String[] { "DoctorId", "FullName", "Specialization", "PhoneNumber", });
    internal_static_Doctor_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Doctor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Doctor_descriptor,
        new java.lang.String[] { "DoctorId", "FirstName", "LastName", "Specialization", "CountryCode", "PhoneNumber", "AvailabilitySlots", });
    internal_static_Slot_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_Slot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Slot_descriptor,
        new java.lang.String[] { "SlotId", "DoctorId", "StartTime", "EndTime", "Booked", });
    internal_static_DoctorList_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_DoctorList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DoctorList_descriptor,
        new java.lang.String[] { "Doctors", });
    internal_static_SlotList_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_SlotList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SlotList_descriptor,
        new java.lang.String[] { "Slots", });
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
