// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor_service.proto

// Protobuf Java Version: 3.25.3
package com.healthcare.api_gateway.service.grpc;

/**
 * Protobuf type {@code Specialization}
 */
public final class Specialization extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Specialization)
    SpecializationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Specialization.newBuilder() to construct.
  private Specialization(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Specialization() {
    specialization_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Specialization();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.healthcare.api_gateway.service.grpc.DoctorServiceOuterClass.internal_static_Specialization_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.healthcare.api_gateway.service.grpc.DoctorServiceOuterClass.internal_static_Specialization_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.healthcare.api_gateway.service.grpc.Specialization.class, com.healthcare.api_gateway.service.grpc.Specialization.Builder.class);
  }

  public static final int SPECIALIZATION_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object specialization_ = "";
  /**
   * <code>string specialization = 1;</code>
   * @return The specialization.
   */
  @java.lang.Override
  public java.lang.String getSpecialization() {
    java.lang.Object ref = specialization_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      specialization_ = s;
      return s;
    }
  }
  /**
   * <code>string specialization = 1;</code>
   * @return The bytes for specialization.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSpecializationBytes() {
    java.lang.Object ref = specialization_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      specialization_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(specialization_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, specialization_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(specialization_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, specialization_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.healthcare.api_gateway.service.grpc.Specialization)) {
      return super.equals(obj);
    }
    com.healthcare.api_gateway.service.grpc.Specialization other = (com.healthcare.api_gateway.service.grpc.Specialization) obj;

    if (!getSpecialization()
        .equals(other.getSpecialization())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SPECIALIZATION_FIELD_NUMBER;
    hash = (53 * hash) + getSpecialization().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.healthcare.api_gateway.service.grpc.Specialization parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.healthcare.api_gateway.service.grpc.Specialization parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.healthcare.api_gateway.service.grpc.Specialization parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.healthcare.api_gateway.service.grpc.Specialization parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.healthcare.api_gateway.service.grpc.Specialization parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.healthcare.api_gateway.service.grpc.Specialization parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.healthcare.api_gateway.service.grpc.Specialization parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.healthcare.api_gateway.service.grpc.Specialization parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.healthcare.api_gateway.service.grpc.Specialization parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.healthcare.api_gateway.service.grpc.Specialization parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.healthcare.api_gateway.service.grpc.Specialization parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.healthcare.api_gateway.service.grpc.Specialization parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.healthcare.api_gateway.service.grpc.Specialization prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Specialization}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Specialization)
      com.healthcare.api_gateway.service.grpc.SpecializationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.healthcare.api_gateway.service.grpc.DoctorServiceOuterClass.internal_static_Specialization_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.healthcare.api_gateway.service.grpc.DoctorServiceOuterClass.internal_static_Specialization_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.healthcare.api_gateway.service.grpc.Specialization.class, com.healthcare.api_gateway.service.grpc.Specialization.Builder.class);
    }

    // Construct using com.healthcare.api_gateway.service.grpc.Specialization.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      specialization_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.healthcare.api_gateway.service.grpc.DoctorServiceOuterClass.internal_static_Specialization_descriptor;
    }

    @java.lang.Override
    public com.healthcare.api_gateway.service.grpc.Specialization getDefaultInstanceForType() {
      return com.healthcare.api_gateway.service.grpc.Specialization.getDefaultInstance();
    }

    @java.lang.Override
    public com.healthcare.api_gateway.service.grpc.Specialization build() {
      com.healthcare.api_gateway.service.grpc.Specialization result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.healthcare.api_gateway.service.grpc.Specialization buildPartial() {
      com.healthcare.api_gateway.service.grpc.Specialization result = new com.healthcare.api_gateway.service.grpc.Specialization(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.healthcare.api_gateway.service.grpc.Specialization result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.specialization_ = specialization_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.healthcare.api_gateway.service.grpc.Specialization) {
        return mergeFrom((com.healthcare.api_gateway.service.grpc.Specialization)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.healthcare.api_gateway.service.grpc.Specialization other) {
      if (other == com.healthcare.api_gateway.service.grpc.Specialization.getDefaultInstance()) return this;
      if (!other.getSpecialization().isEmpty()) {
        specialization_ = other.specialization_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              specialization_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object specialization_ = "";
    /**
     * <code>string specialization = 1;</code>
     * @return The specialization.
     */
    public java.lang.String getSpecialization() {
      java.lang.Object ref = specialization_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        specialization_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string specialization = 1;</code>
     * @return The bytes for specialization.
     */
    public com.google.protobuf.ByteString
        getSpecializationBytes() {
      java.lang.Object ref = specialization_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        specialization_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string specialization = 1;</code>
     * @param value The specialization to set.
     * @return This builder for chaining.
     */
    public Builder setSpecialization(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      specialization_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string specialization = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpecialization() {
      specialization_ = getDefaultInstance().getSpecialization();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string specialization = 1;</code>
     * @param value The bytes for specialization to set.
     * @return This builder for chaining.
     */
    public Builder setSpecializationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      specialization_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Specialization)
  }

  // @@protoc_insertion_point(class_scope:Specialization)
  private static final com.healthcare.api_gateway.service.grpc.Specialization DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.healthcare.api_gateway.service.grpc.Specialization();
  }

  public static com.healthcare.api_gateway.service.grpc.Specialization getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Specialization>
      PARSER = new com.google.protobuf.AbstractParser<Specialization>() {
    @java.lang.Override
    public Specialization parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Specialization> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Specialization> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.healthcare.api_gateway.service.grpc.Specialization getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

