// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor_service.proto

// Protobuf Java Version: 3.25.3
package com.healthcare.api_gateway.service.grpc;

public interface SpecializationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Specialization)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string specialization = 1;</code>
   * @return The specialization.
   */
  java.lang.String getSpecialization();
  /**
   * <code>string specialization = 1;</code>
   * @return The bytes for specialization.
   */
  com.google.protobuf.ByteString
      getSpecializationBytes();
}
