server:
  port:8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/doctor_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  graphql:
    graphiql:
      enabled: true # Enable GraphQL UI at /graphiql
    schema:
      printer:
        enabled: true

# gRPC Server
grpc:
  server:
    port: 9091

# Custom Properties
redisson:
  config: classpath:/redisson.yml
