# for appointment service
server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appointment_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Custom properties
app:
  appointment:
    lock-timeout: 30s # Redis lock timeout

# Redisson config (optional)
redisson:
  config: classpath:/redisson.yml